package scorer

import "strings"

// nicknames maps diminutives to their canonical form.
// All keys are lowercase.
var nicknames = map[string]string{
	"bob":       "robert",
	"bobby":     "robert",
	"rob":       "robert",
	"robbie":    "robert",
	"robby":     "robert",
	"bert":      "robert",
	"bill":      "william",
	"billy":     "william",
	"will":      "william",
	"willy":     "william",
	"willie":    "william",
	"liam":      "william",
	"mike":      "michael",
	"mikey":     "michael",
	"mick":      "michael",
	"mickey":    "michael",
	"jim":       "james",
	"jimmy":     "james",
	"jamie":     "james",
	"dick":      "richard",
	"rick":      "richard",
	"ricky":     "richard",
	"rich":      "richard",
	"richie":    "richard",
	"jack":      "john",
	"johnny":    "john",
	"jon":       "john",
	"joe":       "joseph",
	"joey":      "joseph",
	"tom":       "thomas",
	"tommy":     "thomas",
	"dave":      "david",
	"dan":       "daniel",
	"danny":     "daniel",
	"ed":        "edward",
	"eddie":     "edward",
	"ted":       "edward",
	"teddy":     "edward",
	"ned":       "edward",
	"steve":     "stephen",
	"stevie":    "stephen",
	"chris":     "christopher",
	"matt":      "matthew",
	"matty":     "matthew",
	"tony":      "anthony",
	"andy":      "andrew",
	"drew":      "andrew",
	"alex":      "alexander",
	"al":        "albert",
	"ben":       "benjamin",
	"benny":     "benjamin",
	"charlie":   "charles",
	"chuck":     "charles",
	"charley":   "charles",
	"fred":      "frederick",
	"freddy":    "frederick",
	"frank":     "francis",
	"frankie":   "francis",
	"hank":      "henry",
	"harry":     "henry",
	"hal":       "henry",
	"jerry":     "gerald",
	"gerry":     "gerald",
	"larry":     "lawrence",
	"lenny":     "leonard",
	"leo":       "leonard",
	"nick":      "nicholas",
	"nicky":     "nicholas",
	"pat":       "patrick",
	"paddy":     "patrick",
	"pete":      "peter",
	"petey":     "peter",
	"phil":      "philip",
	"ray":       "raymond",
	"sam":       "samuel",
	"sammy":     "samuel",
	"walt":      "walter",
	"wally":     "walter",
	"ken":       "kenneth",
	"kenny":     "kenneth",
	"ron":       "ronald",
	"ronny":     "ronald",
	"ronnie":    "ronald",
	"don":       "donald",
	"donny":     "donald",
	"donnie":    "donald",
	"greg":      "gregory",
	"doug":      "douglas",
	"dougie":    "douglas",
	"liz":       "elizabeth",
	"lizzy":     "elizabeth",
	"beth":      "elizabeth",
	"betty":     "elizabeth",
	"betsy":     "elizabeth",
	"eliza":     "elizabeth",
	"kate":      "katherine",
	"katie":     "katherine",
	"kathy":     "katherine",
	"cathy":     "katherine",
	"jen":       "jennifer",
	"jenny":     "jennifer",
	"sue":       "susan",
	"susie":     "susan",
	"suzy":      "susan",
	"maggie":    "margaret",
	"meg":       "margaret",
	"peggy":     "margaret",
	"madge":     "margaret",
	"barb":      "barbara",
	"debbie":    "deborah",
	"deb":       "deborah",
	"cindy":     "cynthia",
	"vicky":     "victoria",
	"tori":      "victoria",
	"becky":     "rebecca",
	"becca":     "rebecca",
	"pam":       "pamela",
	"sandy":     "sandra",
	"mandy":     "amanda",
	"abby":      "abigail",
	"gabby":     "gabrielle",
	"gabi":      "gabrielle",
	"steph":     "stephanie",
	"nicki":     "nicole",
}

// expandName returns the canonical form if the name is a known nickname,
// otherwise returns the name unchanged.
func expandName(name string) string {
	lower := strings.ToLower(strings.TrimSpace(name))
	if canonical, ok := nicknames[lower]; ok {
		return canonical
	}
	return lower
}
