package resolve

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fairbearlab/rolodex/internal/model"
	"github.com/fairbearlab/rolodex/internal/parser"
)

// LoadedData holds the parsed report and review contacts.
type LoadedData struct {
	Report         model.Report
	ReviewContacts []model.ParsedContact
}

// LoadReportAndReview reads report.json and review.vcf, returning both.
// This is the shared loader used by both resolve and review commands.
func LoadReportAndReview(reportPath, reviewPath string) (LoadedData, error) {
	reportData, err := os.ReadFile(filepath.Clean(reportPath))
	if err != nil {
		return LoadedData{}, fmt.Errorf("reading report: %w", err)
	}
	var report model.Report
	if err := json.Unmarshal(reportData, &report); err != nil {
		return LoadedData{}, fmt.Errorf("parsing report: %w", err)
	}

	reviewContacts, warnings, err := parser.ParseFile(reviewPath, "review")
	if err != nil {
		return LoadedData{}, fmt.Errorf("reading review contacts: %w", err)
	}
	if err := refuseMalformed(reviewPath, warnings); err != nil {
		return LoadedData{}, err
	}

	return LoadedData{
		Report:         report,
		ReviewContacts: reviewContacts,
	}, nil
}

// refuseMalformed fails when an intermediate file rolodex wrote has entries
// the decoder could not read. Those contacts would be missing from the
// result with no message — the same silent loss merge, run and prune
// report — and the cluster-id check cannot catch it, because a lost card is
// simply absent. The file is regenerated by re-running merge.
func refuseMalformed(path string, warnings []model.Warning) error {
	if len(warnings) == 0 {
		return nil
	}
	lines := make([]string, len(warnings))
	for i, w := range warnings {
		lines[i] = fmt.Sprintf("entry %d: %s", w.Index, w.Message)
	}
	return fmt.Errorf("%s has %d malformed entries whose contacts would be lost (%s); "+
		"re-run merge to regenerate it", path, len(warnings), strings.Join(lines, "; "))
}
